pipeline {
    agent any
    environment{
    PATH = "C:/Program Files/apache-maven-3.9.4/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps{
                  dir('sistemaGerenciamento'){
                    bat "cd"
                  }
            }
            steps {
                bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
    }
}