pipeline {
    agent any
    environment{
    PATH = "C:/Program Files/apache-maven-3.9.4/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
    }
}