pipeline {
    agent any
    environment{
    PATH = "C:/Program Files/apache-maven-3.9.4/bin:$PATH"
    }
    stages {
        stage('Entrar no diretorio'){
            steps{
                dir('sistemaGerenciamento'){
                    bat "pwd"
                }
            }
        }
        stage('Build') {
            steps {
                bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
    }
}